# Generated by Django 6.0 on 2025-12-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_warehouse_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Chuyển động hàng', 'verbose_name_plural': 'Chuyển động hàng'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Kho hàng', 'verbose_name_plural': 'Kho hàng'},
        ),
    ]
